name: Deploy Resource Pack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

    - name: Copy resource pack
      run: |
        rsync -avz --delete path/to/resourcepack/ user@192.168.5.73:/home/limonene/minecraft-data/resourcepacks/

    - name: Notify users
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"リソースパックが更新されました！"}' https://hooks.slack.com/services/your/slack/webhook
