name: Notify Discord

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        curl -X POST -H "Content-Type: application/json" \
        -d "{\"content\": \"リポジトリに変更がプッシュされました！\\nコミットメッセージ: $COMMIT_MESSAGE\"}" \
        $DISCORD_WEBHOOK_URL
